{% set version = "2.9.7" %}

package:
  name: libfuse
  version: {{ version }}

source:
  url: https://github.com/libfuse/libfuse/releases/download/fuse-{{ version }}/fuse-{{ version }}.tar.gz
  sha256: 832432d1ad4f833c20e13b57cf40ce5277a9d33e483205fc63c78111b3358874

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # Seems to be quite stable between minor versions
    # https://abi-laboratory.pro/?view=timeline&l=libfuse
    - {{ pin_subpackage('libfuse', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libfuse${SHLIB_EXT}
    - test -f ${PREFIX}/include/fuse/fuse.h
    - 'mount.fuse 2>&1 | grep -qF usage:'
    - fusermount -V

about:
  home: https://github.com/libfuse/libfuse
  license: GPL-2.0-or-later
  license_file: COPYING
  license_family: GPL
  summary: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface

extra:
  recipe-maintainers:
    - asafkahlon
    - mbargull
    - xmnlab
