{% set name = "libfuse" %}
{% set version = "3.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/fuse-{{ version }}/fuse-{{ version }}.tar.xz
  sha256: 1bafcfd6c66ba35b7b0beb822532a9106eb8409ad6cde988888fde85f89be645

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libfuse3${SHLIB_EXT}
    - test -f ${PREFIX}/include/fuse3/fuse.h

about:
  home: https://github.com/libfuse/libfuse
  license: LGPL-2.1
  license_file: LICENSE
  license_family: LGPL
  summary: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface

extra:
  recipe-maintainers:
    - asafkahlon
